FROM busybox:1.36.0

ARG PLUGIN_VERSION=0.0.1
ARG JAR_DIR=target/


# we also need to add 3rd party dependencies
ADD ${JAR_DIR}/lib/ /provider/
# typical context is the build-dir
ADD ${JAR_DIR}vc-issuer-${PLUGIN_VERSION}.jar /provider/vc-issuer.jar
ADD deploy/service-matrix.properties /provider/service-matrix.properties

RUN mkdir /target

CMD ["cp", "-a",  "/provider/.", "/target/"]