name: Integration-Test

on:
  push

jobs:
  it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '17'
          java-package: jdk

      - name: Execute tests
        id: it-test
        run: |
          mvn clean integration-test -Pintegration-test